# Generated by Django 4.2.6 on 2024-05-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gamedata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.ImageField(upload_to='gamedata/')),
            ],
        ),
    ]
